**Numpy Library**:
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

In [3]:
import numpy as np


In [7]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
# Printing type of arr object
print("Array is of type: ", type(arr))
# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)
# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [9]:
# Creating 3x2 array
array = np.arange(6).reshape(3, 2)
print(array)
print()

[[0 1]
 [2 3]
 [4 5]]



In [12]:
# If no axis mentioned, then it works on the entire array
print(np.argmax(array))

# If axis=1, then it works on each row
print(np.argmax(array, axis=1))

# If axis=0, then it works on each column
print(np.argmax(array, axis=0))

5
[1 1 1]
[2 2]


In [13]:
# Creating a 5x4 array with all zeros
c = np.zeros((5, 4))
print ("An array initialized with all zeros:\n", c)

# Create a constant value array of complex type
d = np.full((5, 5), 6, dtype = 'complex')
print ("An array initialized with all 6s."
            "Array type is complex:\n", d)

# Create an array with random values
e = np.random.random((2, 2))
print ("A random array:\n", e)

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j 6.+0.j 6.+0.j]]
A random array:
 [[0.8789326  0.13881278]
 [0.50476849 0.91101405]]


In [15]:
#arange:It returns evenly spaced values within a given interval.
#Example:
# Create a sequence of integers from 0 to 20 with steps of 3
fun = np.arange(0, 20, 3)
print ("A sequential array with steps of 3:\n", fun)

A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]


In [17]:
#linspace: It returns evenly spaced values within a given interval.
#Example:
# Create a sequence of 10 values in range 0 to 3
fun = np.linspace(0, 3, 10)
print ("A sequential array with 10 values between"
                                 "0 and 3:\n", fun)

A sequential array with 10 values between0 and 3:
 [0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [22]:
#Reshaping array: We can use reshape method to reshape an array.
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [23]:
# Flatten array: We can use flatten method to get a copy of the array collapsed into one dimension.
#Example.1
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()

print ("Original array:\n", arr)
print ("Fattened array:\n", flat_arr)

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
