**Numpy Basic Operations**: In the case of +=, -=, *= operators, the existing array is modified.

In [12]:
import numpy as np

f = np.array([1, 2, 5, 3])

# add 2 to every element
print ("Adding 1 to every element:", f+1)

# subtract 2 from each element
print ("Subtracting 2 from each element:", f-3)

# multiply each element by 5
print ("Multiplying each element by 5:", f*10)

# square each element
print ("Squaring each element:", f**2)

# modify existing array
f *= 2
print ("Doubled each element of original array:", f)


Adding 1 to every element: [2 3 6 4]
Subtracting 2 from each element: [-2 -1  2  0]
Multiplying each element by 5: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]


**NumPy Unary Operators**: It includes sum, min, max, etc.

In [16]:
#Example:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",
                    arr.max(axis = 1))

# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))

# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())

# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [3 6 9]
Column-wise minimum elements: [1 2 3]
Sum of all array elements: 45
Cumulative sum along each row:
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


**NumPy Binary Operators**:These operations apply to the array elementwise and a new array is created.

In [17]:
#Example:

x = np.array([[1, 2],
            [3, 4]])
y = np.array([[4, 3],
            [2, 1]])

# add arrays
print ("Array sum:\n", x + y)

# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", x*y)

# matrix multiplication
print ("Matrix multiplication:\n", x.dot(y))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [15]:
#Sorting of array
#Example:
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(array)
print()

# Sort the whole array
print(np.sort(array, axis=None))

# Sort along each row
print(np.sort(array, axis=1))

# Sort along each column
print(np.sort(array, axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#Example:
x= np.array([1, 2, 3, 4, 5, 6, 0])
print(x)

print(np.argsort(x))

[1 2 3 4 5 6 0]
[6 0 1 2 3 4 5]
